[[bookmark]]
url = "https://sheldonbrown.com/"
title = "Sheldon Brown"
category = "Websites"
desc = "Well organized information about old bicycles. Indispensable if you are doing a fixie conversion of a vintage bicycle. Sheldon Brown the man died in 2008, but the site is still maintained."

[[bookmark]]
url = "https://peter-wiegel.de/"
title = "Peter Wiegel"
category = "Websites"
desc = "Free fonts, some very interesting historical ones, my favicon is Altenglisch."

[[bookmark]]
url = "https://youtube.com/@BadObsessionMotorsport/"
title = "Bad Obsession Motorsport"
category = "Youtube"
desc = "A bizarre and singular car build."

[[bookmark]]
url = "https://youtube.com/@KnitFactoryImpl/"
title = "Knit Factory Impl"
category = "Youtube"
desc = "Knitting machines and information on how you can hack them."

[[bookmark]]
url = "https://youtube.com/@Clickspring/"
title = "Clickspring"
category = "Youtube"
desc = "Top drawer, especially the work on ancient precision clock-making."

[[bookmark]]
url = "https://youtube.com/@AppliedScience/"
title = "Applied Science"
category = "Youtube"

[[bookmark]]
url = "https://youtube.com/@PrimitiveTechnology/"
title = "Primitive Technology"
category = "Youtube"

[[bookmark]]
url = "https://youtube.com/@3Blue1Brown/"
title = "3Blue1Brown"
category = "Youtube"

# [[bookmark]]
# url = "https://jenson.org/"
# title = "Scott Jenson's website"
# category = "Websites"

[[bookmark]]
url = "https://youtube.com/@Blondihacks/"
title = "Blondihacks"
category = "Youtube"
